package project.Personal.content_calender.entity;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@Document(collection = "expenses")  // This will map to the 'expenses' collection in MongoDB
public class ExpenseEntity {

    @Id
    private String id;  // Unique identifier for the expense

    @DBRef  // Reference to the user who made the expense (foreign key)
    private UserEntity user;

    private Double amount;  // Amount of the expense

    private String category;  // Category of the expense (e.g., "Food", "Transportation")

    private String description;  // Description of the expense

    private LocalDateTime date;  // Date when the expense occurred

    @CreatedDate
    private LocalDateTime createdAt;  // Timestamp for when the expense was created

    @LastModifiedDate
    private LocalDateTime updatedAt;  // Timestamp for when the expense was last updated

    // Constructor, getters, setters, etc. are automatically generated by Lombok
    
}
